### PR TITLE
WINDUP-1557 Try increase max open files - soft ulimit -n and complain…

### PR DESCRIPTION
**Pull request by OndraZizka**
… if hard limit is too low.

I've tried locally, but I am no bash master so please check if it makes sense :)

### CODE REVIEW

**Comment by OndraZizka** [comment]
Changed the logic so it does't lower the limit if already higher.

**Comment by OndraZizka** [comment]
Ok this should be the last version :)

**Comment by jsight** [comment]
Merged.

**Comment by jsight** [comment]
Merged: https://github.com/windup/windup-web-distribution/commit/d0342efea78a3d5626052e3d7bb98ff267548aad

**Pull request closed without merging**
