### PR TITLE
[WIP] - 626 - Rebrand the login page in keycloak

### PR DESCRIPTION
**Pull request by klinki**

### CODE REVIEW

**Comment by klinki** [comment]
Depends on https://github.com/windup/windup-web/pull/296

**Comment by jsight** [comment]
Works for me. :)

**Comment by klinki** [comment]
well, it is still not done yet, there is not our branded login page and so on... (again, I couldn't add tags here either :( )

**Comment by jsight** [comment]
Yes, I reverted it as I had merged it by mistake.

Can you send a new PR please? :)

**Pull request merged**
