### PR TITLE
taiga task#790: Add one empty line between text

### PR DESCRIPTION
**Pull request by OndraZizka**
Link only “documentation”
Second line should not be bold

### CODE REVIEW

**Comment by OndraZizka** [comment]
Could you please check, I use RH SSO so I don't see this...

**Comment by mareknovotny** [comment]
it seems ok according to slide 
screenshot from 2017-04-25 14-58-37

**Comment by mareknovotny** [comment]
Please update commit message with the taiga task number

**Comment by klinki** [comment]
@OndraZizka I sent you PR https://github.com/OndraZizka/windup-web-distribution/pull/1 which add little bit more spacing between lines of description. (And I think it matches Marc's slides more).

**Pull request merged**
