### PR TITLE
taiga task #781: adding windows scripts

### PR DESCRIPTION
**Pull request by mareknovotny**

### CODE REVIEW

**Comment by mareknovotny** [comment]
I tried my best, but I can't launch wildfly bat launcher with the script on my testing windows virtualbox.

**Comment by mareknovotny** [comment]
finally figured out that there were 2 issues -> backslash in directory with quotes was escaping the end of directory path and I forgot to replace `$*` with `%*`

**Comment by jsight** [comment]
@mareknovotny - Great... I will test it tonight.

**Comment by mareknovotny** [comment]
@jsight Ok, i found the not pushed changes, but I see the same leading \ in all furnace addons like you wrote on IRC.
I think it is because of this path where is the dot in ` c:\windup\rhamt-web-distribution-3.0.0-SNAPSHOT\.\standalone\data`. I will fix the JBOSS_HOME variable which is the root of that.

**Comment by jsight** [comment]
@mareknovotny - I saw the same behavior with a little test application as well. I think it is just a quirk.

**Comment by jsight** [comment]
@mareknovotny - Tested again and everything works nicely, including the authentication switch scripts. Great work! Thanks!

**Pull request merged**
