### PR TITLE
WIP - Rebranded keycloak login screen

### PR DESCRIPTION
**Pull request by klinki**
This is still work in progress and there is some issue with keycloak for API endpoints. Also it seems login page will change after today's meeting.

### CODE REVIEW

**Comment by klinki** [comment]
@jsight Hmm it seems it is working now - with `api.war` not being in `rhamt-web` directory. I spent almost whole day trying to find out why it doesn't work :( I didn't manage to.

Well, great idea, thanks :)  Now it is almost ready, we just need to add some information to login screen. (Which now looks much more like Marc wants it to look).

**Comment by jsight** [comment]
Great! Let me know when it is ready to review. :)

**Comment by klinki** [comment]
Currently login screen looks like this:
[](https://postimg.org/image/xg76s4uar/)

**Comment by klinki** [comment]
Also this PR depends on https://github.com/windup/windup-keycloak-tool/pull/2  (it switches default theme to `rhamt`) and for auto login to work properly, also on https://github.com/windup/windup-web/pull/300 (it switches mode to `'login-required'`)

**Comment by klinki** [comment]
Ok, so I copied OpenShift as much as possible :)

[](https://postimg.org/image/9vox33sqj/)

(Compare with OpenShift)
[](https://postimg.org/image/3qbj5ufwp/)

**Pull request merged**
